[package]
name = "trustline"
version = "0.1.0"
description = "Trustline Desktop — Secure E2EE messaging client"
authors = ["Trustline Contributors"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "trustline_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crypto_core = { version = "0.1.0", path = "../../../crates/crypto_core" }
base64 = "0.22.1"
uuid = { version = "1.22.0", features = ["v4", "serde"] }
sodiumoxide = "0.2.7"
tauri-plugin-sql = { version = "2.3.2", features = ["sqlite"] }
zeroize = { version = "1.8", features = ["zeroize_derive"] }
rand = "0.9"
keyring = { version = "2", features = ["linux-secret-service"] }
hex = "0.4.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
