ALTER TABLE organizations      FORCE ROW LEVEL SECURITY;
ALTER TABLE users              FORCE ROW LEVEL SECURITY;
ALTER TABLE devices            FORCE ROW LEVEL SECURITY;
ALTER TABLE one_time_pre_keys  FORCE ROW LEVEL SECURITY;
ALTER TABLE encrypted_messages FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs         FORCE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'trustline_app') THEN
    CREATE ROLE trustline_app;
  END IF;
END $$;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO trustline_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO trustline_app;
